config/routes.rb
Rails.application.routes.draw do

  devise_for :end_users,skip: [:passwords,], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  root :to => "public/homes#top"

  namespace :admin do
   root :to => "homes#home"
  end

  namespace :admin do
    resources :end_users, only: [:index, :show, :edit, :update]
  end

  patch 'end_users/withdrawal' => "public/end_users#withdrawal", as: "withdrawal"
  get 'end_users/check' => "public/end_users#check", as: "check"
  get 'end_users/:id/end_user_posts' => "public/end_users#end_user_posts", as: "other_end_user"
  scope module: :public do
    resources :end_users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => "relationships#followings", as: "followings"
      get 'followers' => "relationships#followers", as: "followers"
    end
  end


  get 'posts/popular' => "public/posts#this_week_popular", as: "popular"
  get 'posts/this_month_popular' => "public/posts#this_month_popular", as: "this_month_popular"
  get 'posts/last_month_popular' => "public/posts#last_month_popular", as: "last_month_popular"
  get 'posts/new_posts' => "public/posts#new_posts"
  get 'posts/timeline' => "public/posts#timeline", as: "timeline"
  get 'posts/favorited' => "public/posts#favorited"
  get 'posts/tag/:id' => "public/posts#posts_with_tag", as: "tag"
  scope module: :public do
    resources :posts do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
  end

  namespace :admin do
    resources :posts, only: [:index, :show, :destroy] do
      resources :post_comments, only: [:destroy]
    end
  end

  post 'inquiries/confirm' => "public/inquiries#confirm", as: "confirm"
  resources :inquiries, only: [:new, :create], module: :public

  namespace :admin do
    resources :inquiries, only: [:index, :show, :destroy]
  end

  resources :notifications, only: [:index], module: :public

  get 'searches/search_result' => "public/searches#search_result", as: "search_result"
  get 'searches/search' => "public/searches#search", as: "search"
  get 'searches/all_tags' => "public/searches#all_tags", as: "tags"


end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :end_user
  has_many :image_files, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_end_users, through: :favorites, source: :end_user
  has_many :post_comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  accepts_attachments_for :image_files, attachment: :image, append: true

  acts_as_taggable_on :tags
  acts_as_taggable_on :skills, :interests

  validates :title, presence: true, length: { maximum: 50}
  validates :text, presence: true, length: { maximum: 200}
  validates :image_files, presence: true


  def favorited_by?(end_user)
    favorites.where(end_user_id: end_user.id).exists?
  end

  #いいねがされたとき通知を作る
  def create_notification_favorite!(current_end_user)
    temp = Notification.where(["visitor_id = ? and visited_id and post_id = ? and action = ?", current_end_user.id, end_user.id, 'favorite'])
    if temp.blank?
      notification = current_end_user.active_notifications.new(
        post_id: id,
        visited_id: end_user_id,
        action: 'favorite'
      )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  #投稿にコメントがされたときに通知を作る
  def create_notification_comment!(current_end_user, post_comment_id)
    temp_ids = PostComment.where(post_id: id).where.not("end_user_id=? or end_user_id=?", current_end_user.id, end_user_id).select(:end_user_id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_end_user, post_comment_id, temp_id['end_user_id'])
    end
    save_notification_comment!(current_end_user, post_comment_id, end_user_id)
  end

  def save_notification_comment!(current_end_user, post_comment_id, visited_id)
    notification = current_end_user.active_notifications.new(
      post_id: id,
      post_comment_id: post_comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col offset-1">
      <h3>投稿一覧</h3>
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>タイトル</th>
              <th>投稿者</th>
              <th></th>
            </tr>
          </thead>
          <% @posts.each do |post| %>
            <tbody>
              <tr>
                <td>
                  <% post.image_files.first(1).each do |image| %>
                    <%= attachment_image_tag image, :image, size: "50x50" %>
                  <% end %>
                </td>
                <td><%= post.title %></td>
                <td><%= post.end_user.name %></td>
                <td>
                  <%= link_to "詳細へ", admin_post_path(post), class: "btn btn-success" %>
                </td>
              </tr>
            </tbody>
          <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 offset-2">
      <div class="row g-0">
        <div class="col-8">
          <div class="carousel_slide" id="post_image" data-ride="carousel">
            <ol class="carousel-indicators">
              <li data-target="#post_image" data-slide-to="0" class="active"></li>
              <% @post.image_files.drop(1).count.times do |index| %>
                <li data-target="#post_image" data-slide-to="#{index}"></li>
              <% end %>
            </ol>

            <div class="carousel-inner">
              <div class="carousel-item active">
                <% @post.image_files.first(1).each do |image| %>
                  <%= attachment_image_tag image, :image, size: "500x450", class: "carousel_image"  %>
                <% end %>
              </div>
              <% @post.image_files.drop(1).each do |image| %>
                <div class="carousel-item">
                  <%= attachment_image_tag image, :image, size: "500x450", class: "carousel_image" %>
                </div>
              <% end %>
            </div>
            <a href="#post_image" class="carousel-control-prev" data-slide="prev">
              <span class="carousel-control-prev-icon"></span>
              <span class="sr-only">前へ</span>
            </a>
            <a href="#post_image" class="carousel-control-next" data-slide="next">
              <span class="carousel-control-next-icon"></span>
              <span class="sr-only">次へ</span>
            </a>
　　　　　　</div>
        </div>
        <div class="col-4">
          <div class="card-body">
            <div class="card-title">
              <%= link_to admin_end_user_path(@post.end_user) do %>
                <%= attachment_image_tag @post.end_user, :profile_image, width: "30%", heigth: "30%", fallback: "no_image.jpg", class: "circle"%>
              <% end %>
              <%= @post.end_user.name %>
            </div>
            <div class="row">
              <%= @post.text %>
            </div>
            <div class="row">
              <% @post.tag_list.each do |tag| %>
                <%= link_to posts_path(tag) do %>
                  #<%= tag %>
                <% end %>
                 &nbsp;
              <% end %>
            </div>
            <div class="row">
              <div class="col-auto">
                ♥<%= @post.favorites.count %>
              </div>
              <div class="col">
                <%= @post.created_at.strftime("%Y/%m/%d") %>
              </div>
            </div>
            <div class="row">
              <%= link_to "投稿を削除", admin_post_path(@post), method: :delete, class: "btn btn-danger" %>
            </div>
          </div>
        </div>
      </div>
      <br>
      <div class="card">
        <div class="card-header">コメント (<%= @post.post_comments.count %>)</div>
        <div class="card-body">
          <% if @post.post_comments.blank? %>
            <p class="text-center">コメントはありません</p>
          <% else %>
            <% @post.post_comments.each do |post_comment| %>
              <tbody>
                <tr>
                  <td>
                    <%= link_to end_user_path(post_comment.end_user_id) do %>
                      <%= attachment_image_tag post_comment.end_user.profile_image, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40", class: "circle" %>
                    <% end %>
                  </td>
                  <td>
                    <%= post_comment.comment %>
                  </td>
                  <td>
                    <%= link_to "Destroy", admin_post_post_comment_path(@post, post_comment), method: :delete, local: true, class: "btn btn-danger" %>
                  </td>
                  <td>
                    <%= post_comment.created_at.strftime("%Y/%m/%d") %>
                  </td>
                </tr>
              </tbody>
            </table>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>