config/routes.rb
Rails.application.routes.draw do

  devise_for :end_users,skip: [:passwords,], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  root :to => "public/homes#top"

  namespace :admin do
   root :to => "homes#home"
  end

  namespace :admin do
    resources :end_users, only: [:index, :show, :edit, :update]
  end

  patch 'end_users/withdrawal' => "public/end_users#withdrawal", as: "withdrawal"
  get 'end_users/check' => "public/end_users#check", as: "check"
  get 'end_users/:id/end_user_posts' => "public/end_users#end_user_posts", as: "other_end_user"
  scope module: :public do
    resources :end_users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => "relationships#followings", as: "followings"
      get 'followers' => "relationships#followers", as: "followers"
    end
  end


  get 'posts/popular' => "public/posts#this_week_popular", as: "popular"
  get 'posts/this_month_popular' => "public/posts#this_month_popular", as: "this_month_popular"
  get 'posts/last_month_popular' => "public/posts#last_month_popular", as: "last_month_popular"
  get 'posts/new_posts' => "public/posts#new_posts"
  get 'posts/timeline' => "public/posts#timeline", as: "timeline"
  get 'posts/favorited' => "public/posts#favorited"
  get 'posts/tag/:id' => "public/posts#posts_with_tag", as: "tag"
  scope module: :public do
    resources :posts do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
  end

  namespace :admin do
    resources :posts, only: [:index, :show, :destroy] do
      resources :post_comments, only: [:destroy]
    end
  end

  post 'inquiries/confirm' => "public/inquiries#confirm", as: "confirm"
  resources :inquiries, only: [:new, :create], module: :public

  namespace :admin do
    resources :inquiries, only: [:index, :show, :destroy]
  end

  resources :notifications, only: [:index], module: :public

  get 'searches/search_result' => "public/searches#search_result", as: "search_result"
  get 'searches/search' => "public/searches#search", as: "search"
  get 'searches/all_tags' => "public/searches#all_tags", as: "tags"


end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :active_notifications, class_name: "Notification", foreign_key: "visitor_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy
  has_many :inquiries, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  attachment :profile_image

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }

  def follow(end_user_id)
    relationships.create(followed_id: end_user_id)
  end

  def unfollow(end_user_id)
    relationships.find_by(followed_id: end_user_id).destroy
  end

  def following?(end_user)
    followings.include?(end_user)
  end

  #フォローされたときに通知を作成
  def create_notification_follow!(current_end_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ?", current_end_user.id, id, 'follow'])
    if temp.blank?
      notification = current_end_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

end

app/controllers/admin/end_users_controller.rb
class Admin::EndUsersController < ApplicationController
  def index
    @end_users = EndUser.all
  end

  def show
    @end_user = EndUser.find(params[:id])
  end

  def edit
    @end_user = EndUser.find(params[:id])
  end

  def update
    @end_user = EndUser.find(params[:id])
    if @end_user.update(end_user_params)
      redirect_to admin_end_user_path(@end_user)
    else
      render :edit
    end
  end

  private

  def end_user_params
    params.require(:end_user).permit(:name, :email, :profile_image, :is_deleted)
  end

end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/views/admin/end_users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 offset-2">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Edit user info</h3>
            <%= form_with model: [:admin, @end_user], local: true do |f| %>
              <label for="inputEndUserName">ユーザーネーム</label>
              <%= f.text_field :name, autofocus: true, id: "inputEndUserName", class: "form-control" %>
              <br>
              <label for="inputEmail">メールアドレス</label>
              <%= f.text_field :email, autofocus: true, id: "inputEmail", class: "form-control" %>
              <br>
              <label class="col col-form-label">ユーザーステータス</label>
              <div class="col">
                <%= f.radio_button :is_deleted, false %>
                <%= f.label :is_deleted, '登録済', value: false %>
                <%= f.radio_button :is_deleted, true %>
                <%= f.label :is_deleted, '退会', value: true %>
              </div>
              <%= f.submit "編集", class: "btn btn-success" %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/end_users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col offset-1">
      <h3>ユーザー一覧</h3>
      <table class="table">
        <thead>
          <tr>
            <th>ユーザー名</th>
            <th></th>
          </tr>
        </thead>
        <% @end_users.each do |end_user| %>
          <tbody>
            <tr>
              <td>
                <%= attachment_image_tag end_user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40", class: "circle" %>

                <%= end_user.name %>
              </td>
              <td>
                <%= link_to "詳細へ", admin_end_user_path(end_user), class: "btn btn-success" %>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/end_users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 offset-2">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">User info</h3>
        </div>
        <div class="row">
          <div class="col-3 offset-1">
            <%= attachment_image_tag @end_user, :profile_image, size: "150x150", fallback: "no_image.jpg", class: "circle"%>
            <br>
            <div class="text-center my-1">
              <strong><%= @end_user.name %></strong>
            </div>
          </div>
          <div class="col-5 offset-1">
            <br>
            <div class="row my-3">
              <div class="col-auto">
                メールアドレス
              </div>
              <div class="col-auto offset-1">
                <%= @end_user.email %>
              </div>
            </div>
            <div class="row my-3">
              <div class="col-auto">
                会員ステータス
              </div>
              <div class="col-auto offset-1">
                <% if @end_user.is_deleted == false %>
                  <p class="text-success">登録済</p>
                <% else %>
                  <p class="text-default">退会</p>
                <% end %>
              </div>
            </div>
            <div class="row mb-3">
              <%= link_to "ユーザー情報編集", edit_admin_end_user_path(@end_user), class: "btn btn-secondary btn-block" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>