config/routes.rb
Rails.application.routes.draw do

  devise_for :end_users,skip: [:passwords,], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  root :to => "public/homes#top"

  namespace :admin do
   root :to => "homes#home"
  end

  namespace :admin do
    resources :end_users, only: [:index, :show, :edit, :update]
  end

  patch 'end_users/withdrawal' => "public/end_users#withdrawal", as: "withdrawal"
  get 'end_users/check' => "public/end_users#check", as: "check"
  get 'end_users/:id/end_user_posts' => "public/end_users#end_user_posts", as: "other_end_user"
  scope module: :public do
    resources :end_users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => "relationships#followings", as: "followings"
      get 'followers' => "relationships#followers", as: "followers"
    end
  end


  get 'posts/popular' => "public/posts#this_week_popular", as: "popular"
  get 'posts/this_month_popular' => "public/posts#this_month_popular", as: "this_month_popular"
  get 'posts/last_month_popular' => "public/posts#last_month_popular", as: "last_month_popular"
  get 'posts/new_posts' => "public/posts#new_posts"
  get 'posts/timeline' => "public/posts#timeline", as: "timeline"
  get 'posts/favorited' => "public/posts#favorited"
  get 'posts/tag/:id' => "public/posts#posts_with_tag", as: "tag"
  scope module: :public do
    resources :posts do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
  end

  namespace :admin do
    resources :posts, only: [:index, :show, :destroy] do
      resources :post_comments, only: [:destroy]
    end
  end

  post 'inquiries/confirm' => "public/inquiries#confirm", as: "confirm"
  resources :inquiries, only: [:new, :create], module: :public

  namespace :admin do
    resources :inquiries, only: [:index, :show, :destroy]
  end

  resources :notifications, only: [:index], module: :public

  get 'searches/search_result' => "public/searches#search_result", as: "search_result"
  get 'searches/search' => "public/searches#search", as: "search"
  get 'searches/all_tags' => "public/searches#all_tags", as: "tags"


end

app/views/layouts/_navlink_bar.html.erb
<div class="list-group text-center">
  <% if current_page?(timeline_path) do %>
    <%= link_to "Timeline", timeline_path, class: "list-group-item list-group-item-action active" %>
  <% else %>
    <%= link_to "Timeline", timeline_path, class: "list-group-item list-group-item-action" %>
  <% end %>
  <% if current_page?(popular_path || this_month_popular_path || last_month_popular) do %>
    <%= link_to "Popular", popular_path, class: "list-group-item list-group-item-action active" %>
  <% else %>
    <%= link_to "Popular", popular_path, class: "list-group-item list-group-item-action" %>
  <% end %>
  <% if current_page?(posts_new_posts_path) do %>
    <%= link_to "New", posts_new_posts_path, class: "list-group-item list-group-item-action active" %>
  <% else %>
    <%= link_to "New", posts_new_posts_path, class: "list-group-item list-group-item-action" %>
  <% end %>
  <% if current_page?(search_path) do %>
    <%= link_to "Search", search_path, class: "list-group-item list-group-item-action active" %>
  <% else %>
    <%= link_to "Search", search_path, class: "list-group-item list-group-item-action" %>
  <% end %>
  <% if current_page?(new_post_path) do %>
    <%= link_to "Create post", new_post_path, class: "list-group-item list-group-item-action active" %>
  <% else %>
    <%= link_to "Create post", new_post_path, class: "list-group-item list-group-item-action" %>
  <% end %>
  <% if current_page?(posts_favorited_path) do %>
    <%= link_to "Your favorite posts", posts_favorited_path, class: "list-group-item list-group-item-action active" %>
  <% else %>
    <%= link_to "Your favorite posts", posts_favorited_path, class: "list-group-item list-group-item-action" %>
  <% end %>
  <% if current_page?(posts_path) do %>
    <%= link_to "Your posts", posts_path, class: "list-group-item list-group-item-action active" %>
  <% else %>
    <%= link_to "Your posts", posts_path, class: "list-group-item list-group-item-action" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>Cat.Com</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="sticky-top">
      <nav class="navbar navbar-light bg-dark">
        <a class="navbar-brand text-white" href="/">
          <%= image_tag 'Catcom_logo.jpg' , width: "25%", height: "25%" %>
        </a>
        <div class="col text-right text-light">
          <% if end_user_signed_in? %>
            Hello,
            <%= link_to end_user_path(current_end_user), class: "text-light" do %>
              <%= current_end_user.name %>!
            <% end %>
              <%= image_tag 'catlogo_3.png', size: "65x25" %>
          <% end %>
        </div>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav mr-auto my-2 my-lg-0" style="max-height: 100px;">
            <li class="nav-item">
              <% if admin_signed_in? %>
                <li class="nav-item">
                  <%= link_to admin_root_path, class: "text-light" do %>
                    <i class="fas fa-envelope-open-text"></i> Messages from users
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to admin_end_users_path, class: "text-light" do %>
                    <i class="fas fa-users"></i> Users
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to admin_posts_path, class: "text-light" do %>
                    <i class="fas fa-cat"></i> Posts
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_admin_session_path, method: :delete, class: "text-light" do %>
                    <i class="fas fa-sign-out-alt"></i> Log out
                  <% end %>
                </li>
              <% elsif end_user_signed_in? %>
                <li class="nav-item">
                  <%= link_to end_user_path(current_end_user), class: "text-light" do %>
                    <i class="fas fa-user"></i> Your info
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to notifications_path, class: "text-light" do %>
                    <i class="fas fa-bell"></i> Notification
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_inquiry_path, class: "text-light" do %>
                    <i class="fas fa-paper-plane"></i> Contact us
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_end_user_session_path, method: :delete, class: "text-light" do %>
                    <i class="fas fa-sign-out-alt"></i> Log out
                  <% end %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to new_end_user_registration_path, class: "text-light" do %>
                    <i class="fas fa-user-plus"></i> Sign up
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_end_user_session_path, class: "text-light" do %>
                    <i class="fas fa-sign-in-alt"></i> Log in
                  <% end %>
                </li>
              <% end %>
            </li>
          </ur>
        </div>
      </nav>
    </header>
    <br>
    <%= yield %>
    <br>
    <footer class="fixed-bottom  bg-dark">
      <div class="container">
        <div class="row">
          <div class="mx-auto">
            <p class="text-white">CopyRight Cat.com</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>